@startuml
class CostomerManger {
- List<Costomer> customers
- {static} int nextId
+ void GetConstomerData()
+ boolean register(String,int,String)
+ Costomer login(String,String)
- Costomer findByName(String)
+ Costomer findById(int)
+ List<Costomer> searchByName(String)
+ boolean updateCustomerById(int,String,Integer,String)
+ List<Costomer> getAllCustomers()
+ int getCustomerCount()
}


class MyShop {
- {static} CostomerManger customerManager
- {static} Scanner input
- {static} Costomer currentUser
+ {static} void main(String[])
+ {static} void showMainMenu()
- {static} String setRandomPin()
- {static} boolean isValidPin()
+ {static} void login()
+ {static} void register()
+ {static} void customerInfoManage()
+ {static} void modifyCustomerById()
+ {static} void Operate()
}


enum Viplevel {
+  Silver
+  Gold
+  Platinum
}

class Costomer {
~ String Name
~ int PhoneNumber
~ int id
~ Viplevel Level
~ String time
~ String password
+ String getName()
+ void setName(String)
+ int getPhoneNumber()
+ void setPhoneNumber(int)
+ int getId()
+ void setId(int)
+ Viplevel getLevel()
+ void setLevel(Viplevel)
+ String getTime()
+ void setTime(String)
+ String getPassword()
+ void setPassword(String)
+ String toString()
}


@enduml